transcript on
if {[file exists rtl_work]} {
	vdel -lib rtl_work -all
}
vlib rtl_work
vmap work rtl_work

vlib Computer_System
vmap Computer_System Computer_System
vlog -vlog01compat -work Computer_System +incdir+C:/Users/rat83/Documents/GitHub/FPGA-Project/VGA_to_M10k/verilog/Computer_System/synthesis {C:/Users/rat83/Documents/GitHub/FPGA-Project/VGA_to_M10k/verilog/Computer_System/synthesis/Computer_System.v}
vlog -vlog01compat -work Computer_System +incdir+C:/Users/rat83/Documents/GitHub/FPGA-Project/VGA_to_M10k/verilog/Computer_System/synthesis/submodules {C:/Users/rat83/Documents/GitHub/FPGA-Project/VGA_to_M10k/verilog/Computer_System/synthesis/submodules/altera_reset_controller.v}
vlog -vlog01compat -work Computer_System +incdir+C:/Users/rat83/Documents/GitHub/FPGA-Project/VGA_to_M10k/verilog/Computer_System/synthesis/submodules {C:/Users/rat83/Documents/GitHub/FPGA-Project/VGA_to_M10k/verilog/Computer_System/synthesis/submodules/Computer_System_vga_pio.v}
vlog -vlog01compat -work Computer_System +incdir+C:/Users/rat83/Documents/GitHub/FPGA-Project/VGA_to_M10k/verilog/Computer_System/synthesis/submodules {C:/Users/rat83/Documents/GitHub/FPGA-Project/VGA_to_M10k/verilog/Computer_System/synthesis/submodules/Computer_System_m10k_pll.v}
vlog -vlog01compat -work Computer_System +incdir+C:/Users/rat83/Documents/GitHub/FPGA-Project/VGA_to_M10k/verilog/Computer_System/synthesis/submodules {C:/Users/rat83/Documents/GitHub/FPGA-Project/VGA_to_M10k/verilog/Computer_System/synthesis/submodules/Computer_System_System_PLL.v}
vlog -vlog01compat -work Computer_System +incdir+C:/Users/rat83/Documents/GitHub/FPGA-Project/VGA_to_M10k/verilog/Computer_System/synthesis/submodules {C:/Users/rat83/Documents/GitHub/FPGA-Project/VGA_to_M10k/verilog/Computer_System/synthesis/submodules/altera_up_avalon_reset_from_locked_signal.v}
vlog -vlog01compat -work Computer_System +incdir+C:/Users/rat83/Documents/GitHub/FPGA-Project/VGA_to_M10k/verilog/Computer_System/synthesis/submodules {C:/Users/rat83/Documents/GitHub/FPGA-Project/VGA_to_M10k/verilog/Computer_System/synthesis/submodules/Computer_System_System_PLL_sys_pll.v}
vlog -vlog01compat -work Computer_System +incdir+C:/Users/rat83/Documents/GitHub/FPGA-Project/VGA_to_M10k/verilog/Computer_System/synthesis/submodules {C:/Users/rat83/Documents/GitHub/FPGA-Project/VGA_to_M10k/verilog/Computer_System/synthesis/submodules/Computer_System_ARM_A9_HPS.v}
vlog -vlog01compat -work Computer_System +incdir+C:/Users/rat83/Documents/GitHub/FPGA-Project/VGA_to_M10k/verilog/Computer_System/synthesis/submodules {C:/Users/rat83/Documents/GitHub/FPGA-Project/VGA_to_M10k/verilog/Computer_System/synthesis/submodules/Computer_System_ARM_A9_HPS_hps_io.v}
vlog -vlog01compat -work Computer_System +incdir+C:/Users/rat83/Documents/GitHub/FPGA-Project/VGA_to_M10k/verilog/Computer_System/synthesis/submodules {C:/Users/rat83/Documents/GitHub/FPGA-Project/VGA_to_M10k/verilog/Computer_System/synthesis/submodules/hps_sdram.v}
vlog -vlog01compat -work Computer_System +incdir+C:/Users/rat83/Documents/GitHub/FPGA-Project/VGA_to_M10k/verilog/Computer_System/synthesis/submodules {C:/Users/rat83/Documents/GitHub/FPGA-Project/VGA_to_M10k/verilog/Computer_System/synthesis/submodules/altera_mem_if_hhp_qseq_synth_top.v}
vlog -vlog01compat -work Computer_System +incdir+C:/Users/rat83/Documents/GitHub/FPGA-Project/VGA_to_M10k/verilog/Computer_System/synthesis/submodules {C:/Users/rat83/Documents/GitHub/FPGA-Project/VGA_to_M10k/verilog/Computer_System/synthesis/submodules/hps_sdram_p0_acv_hard_addr_cmd_pads.v}
vlog -vlog01compat -work Computer_System +incdir+C:/Users/rat83/Documents/GitHub/FPGA-Project/VGA_to_M10k/verilog/Computer_System/synthesis/submodules {C:/Users/rat83/Documents/GitHub/FPGA-Project/VGA_to_M10k/verilog/Computer_System/synthesis/submodules/hps_sdram_p0_acv_hard_io_pads.v}
vlog -vlog01compat -work Computer_System +incdir+C:/Users/rat83/Documents/GitHub/FPGA-Project/VGA_to_M10k/verilog/Computer_System/synthesis/submodules {C:/Users/rat83/Documents/GitHub/FPGA-Project/VGA_to_M10k/verilog/Computer_System/synthesis/submodules/hps_sdram_p0_acv_hard_memphy.v}
vlog -vlog01compat -work Computer_System +incdir+C:/Users/rat83/Documents/GitHub/FPGA-Project/VGA_to_M10k/verilog/Computer_System/synthesis/submodules {C:/Users/rat83/Documents/GitHub/FPGA-Project/VGA_to_M10k/verilog/Computer_System/synthesis/submodules/hps_sdram_p0_acv_ldc.v}
vlog -vlog01compat -work Computer_System +incdir+C:/Users/rat83/Documents/GitHub/FPGA-Project/VGA_to_M10k/verilog/Computer_System/synthesis/submodules {C:/Users/rat83/Documents/GitHub/FPGA-Project/VGA_to_M10k/verilog/Computer_System/synthesis/submodules/hps_sdram_p0_altdqdqs.v}
vlog -vlog01compat -work Computer_System +incdir+C:/Users/rat83/Documents/GitHub/FPGA-Project/VGA_to_M10k/verilog/Computer_System/synthesis/submodules {C:/Users/rat83/Documents/GitHub/FPGA-Project/VGA_to_M10k/verilog/Computer_System/synthesis/submodules/hps_sdram_p0_clock_pair_generator.v}
vlog -vlog01compat -work Computer_System +incdir+C:/Users/rat83/Documents/GitHub/FPGA-Project/VGA_to_M10k/verilog/Computer_System/synthesis/submodules {C:/Users/rat83/Documents/GitHub/FPGA-Project/VGA_to_M10k/verilog/Computer_System/synthesis/submodules/hps_sdram_p0_generic_ddio.v}
vlog -vlog01compat -work work +incdir+C:/Users/rat83/Documents/GitHub/FPGA-Project/VGA_to_M10k/verilog {C:/Users/rat83/Documents/GitHub/FPGA-Project/VGA_to_M10k/verilog/DE1_SoC_Computer.v}
vlog -vlog01compat -work work +incdir+C:/Users/rat83/Documents/GitHub/FPGA-Project/VGA_to_M10k/verilog {C:/Users/rat83/Documents/GitHub/FPGA-Project/VGA_to_M10k/verilog/hex_decoder.v}
vlog -sv -work Computer_System +incdir+C:/Users/rat83/Documents/GitHub/FPGA-Project/VGA_to_M10k/verilog/Computer_System/synthesis/submodules {C:/Users/rat83/Documents/GitHub/FPGA-Project/VGA_to_M10k/verilog/Computer_System/synthesis/submodules/Computer_System_irq_mapper.sv}
vlog -sv -work Computer_System +incdir+C:/Users/rat83/Documents/GitHub/FPGA-Project/VGA_to_M10k/verilog/Computer_System/synthesis/submodules {C:/Users/rat83/Documents/GitHub/FPGA-Project/VGA_to_M10k/verilog/Computer_System/synthesis/submodules/altdq_dqs2_acv_connect_to_hard_phy_cyclonev.sv}
vlog -sv -work Computer_System +incdir+C:/Users/rat83/Documents/GitHub/FPGA-Project/VGA_to_M10k/verilog/Computer_System/synthesis/submodules {C:/Users/rat83/Documents/GitHub/FPGA-Project/VGA_to_M10k/verilog/Computer_System/synthesis/submodules/altera_mem_if_dll_cyclonev.sv}
vlog -sv -work Computer_System +incdir+C:/Users/rat83/Documents/GitHub/FPGA-Project/VGA_to_M10k/verilog/Computer_System/synthesis/submodules {C:/Users/rat83/Documents/GitHub/FPGA-Project/VGA_to_M10k/verilog/Computer_System/synthesis/submodules/altera_mem_if_hard_memory_controller_top_cyclonev.sv}
vlog -sv -work Computer_System +incdir+C:/Users/rat83/Documents/GitHub/FPGA-Project/VGA_to_M10k/verilog/Computer_System/synthesis/submodules {C:/Users/rat83/Documents/GitHub/FPGA-Project/VGA_to_M10k/verilog/Computer_System/synthesis/submodules/altera_mem_if_oct_cyclonev.sv}
vlog -sv -work Computer_System +incdir+C:/Users/rat83/Documents/GitHub/FPGA-Project/VGA_to_M10k/verilog/Computer_System/synthesis/submodules {C:/Users/rat83/Documents/GitHub/FPGA-Project/VGA_to_M10k/verilog/Computer_System/synthesis/submodules/hps_sdram_p0.sv}
vlog -sv -work Computer_System +incdir+C:/Users/rat83/Documents/GitHub/FPGA-Project/VGA_to_M10k/verilog/Computer_System/synthesis/submodules {C:/Users/rat83/Documents/GitHub/FPGA-Project/VGA_to_M10k/verilog/Computer_System/synthesis/submodules/hps_sdram_pll.sv}
vlog -sv -work Computer_System +incdir+C:/Users/rat83/Documents/GitHub/FPGA-Project/VGA_to_M10k/verilog/Computer_System/synthesis/submodules {C:/Users/rat83/Documents/GitHub/FPGA-Project/VGA_to_M10k/verilog/Computer_System/synthesis/submodules/Computer_System_ARM_A9_HPS_hps_io_border.sv}
vlog -sv -work Computer_System +incdir+C:/Users/rat83/Documents/GitHub/FPGA-Project/VGA_to_M10k/verilog/Computer_System/synthesis/submodules {C:/Users/rat83/Documents/GitHub/FPGA-Project/VGA_to_M10k/verilog/Computer_System/synthesis/submodules/Computer_System_ARM_A9_HPS_fpga_interfaces.sv}
vlog -sv -work work +incdir+C:/Users/rat83/Documents/GitHub/FPGA-Project/VGA_to_M10k/verilog/boid_accelerator {C:/Users/rat83/Documents/GitHub/FPGA-Project/VGA_to_M10k/verilog/boid_accelerator/boid_accelerator.sv}

